### ISSUE TITLE
BOM part number

### ISSUE THREAD

**Issue by musakajima** [joshajohnson/pro-micro-c#1]
hi josh,

I wanna try to make your version usb c pro micro version for my redox keyboard, already list material from your assembly file but i don't have any clue to get the right components.
do you mind to give detail references for the components (part number)? i wanna source them from lcsc

**Comment by joshajohnson** [comment]
I have exported the BOM from EESchema and can be found [here](https://github.com/joshajohnson/sea-micro/blob/master/hardware/0.3/outputs/bom.csv).
