### ISSUE TITLE
Lines in error layer in v0.4.

### ISSUE THREAD

**Issue by OrvilleQ** [joshajohnson/pro-micro-c#3]
![image](https://user-images.githubusercontent.com/21377465/131214112-f61d6a46-19af-4260-9ccd-3cc9450c0128.png)

This happend because lines locate at (122, 94) and (124, 102) are in the wrong layer.

![image](https://user-images.githubusercontent.com/21377465/131214228-d4de7562-d145-4560-8b4d-110f513921c8.png)

They should in Edge.Cuts.

I'm making a patch now, will open a pull request soon.

**Comment by joshajohnson** [comment]
Thanks for catching this, happy to fix it myself if you've got other things to do, otherwise will happily merge the PR :)

**Comment by OrvilleQ** [comment]
Pull request has opend.

I am new to PCB design, and I'm learning how to deal with ATMEGA32U4 from your project now.

Happy to help with you and thanks for making this project.

**Comment by joshajohnson** [comment]
Resolved in https://github.com/joshajohnson/sea-micro/commit/24f7533860adf2eb480226300e7bdf9810df4f85.

Thanks for the fix!
